services:
  app:
    build: .
    image: webhook-migration-backend
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - ./prisma:/usr/src/app/prisma/
      - ./.env:/usr/src/app/.env
    environment:
      NODE_ENV: development
